/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MangaIdRouteImport } from './routes/manga.$id'
import { Route as ChapterIdRouteImport } from './routes/chapter.$id'
import { Route as ApiCoversSplatRouteImport } from './routes/api.covers.$'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MangaIdRoute = MangaIdRouteImport.update({
  id: '/manga/$id',
  path: '/manga/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChapterIdRoute = ChapterIdRouteImport.update({
  id: '/chapter/$id',
  path: '/chapter/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoversSplatRoute = ApiCoversSplatRouteImport.update({
  id: '/api/covers/$',
  path: '/api/covers/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/chapter/$id': typeof ChapterIdRoute
  '/manga/$id': typeof MangaIdRoute
  '/api/covers/$': typeof ApiCoversSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/chapter/$id': typeof ChapterIdRoute
  '/manga/$id': typeof MangaIdRoute
  '/api/covers/$': typeof ApiCoversSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/chapter/$id': typeof ChapterIdRoute
  '/manga/$id': typeof MangaIdRoute
  '/api/covers/$': typeof ApiCoversSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/search' | '/chapter/$id' | '/manga/$id' | '/api/covers/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/search' | '/chapter/$id' | '/manga/$id' | '/api/covers/$'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/chapter/$id'
    | '/manga/$id'
    | '/api/covers/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  ChapterIdRoute: typeof ChapterIdRoute
  MangaIdRoute: typeof MangaIdRoute
  ApiCoversSplatRoute: typeof ApiCoversSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manga/$id': {
      id: '/manga/$id'
      path: '/manga/$id'
      fullPath: '/manga/$id'
      preLoaderRoute: typeof MangaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapter/$id': {
      id: '/chapter/$id'
      path: '/chapter/$id'
      fullPath: '/chapter/$id'
      preLoaderRoute: typeof ChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/covers/$': {
      id: '/api/covers/$'
      path: '/api/covers/$'
      fullPath: '/api/covers/$'
      preLoaderRoute: typeof ApiCoversSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  ChapterIdRoute: ChapterIdRoute,
  MangaIdRoute: MangaIdRoute,
  ApiCoversSplatRoute: ApiCoversSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
