/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdultRouteImport } from './routes/adult'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyComicIdRouteImport } from './routes/my-comic.$id'
import { Route as MyChapterIdRouteImport } from './routes/my-chapter.$id'
import { Route as MangaIdRouteImport } from './routes/manga.$id'
import { Route as ChapterIdRouteImport } from './routes/chapter.$id'
import { Route as ApiImageRouteImport } from './routes/api.image'
import { Route as ApiMangadexSplatRouteImport } from './routes/api.mangadex.$'
import { Route as ApiCoversSplatRouteImport } from './routes/api.covers.$'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdultRoute = AdultRouteImport.update({
  id: '/adult',
  path: '/adult',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyComicIdRoute = MyComicIdRouteImport.update({
  id: '/my-comic/$id',
  path: '/my-comic/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MyChapterIdRoute = MyChapterIdRouteImport.update({
  id: '/my-chapter/$id',
  path: '/my-chapter/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MangaIdRoute = MangaIdRouteImport.update({
  id: '/manga/$id',
  path: '/manga/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChapterIdRoute = ChapterIdRouteImport.update({
  id: '/chapter/$id',
  path: '/chapter/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageRoute = ApiImageRouteImport.update({
  id: '/api/image',
  path: '/api/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMangadexSplatRoute = ApiMangadexSplatRouteImport.update({
  id: '/api/mangadex/$',
  path: '/api/mangadex/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoversSplatRoute = ApiCoversSplatRouteImport.update({
  id: '/api/covers/$',
  path: '/api/covers/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/adult': typeof AdultRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/upload': typeof UploadRoute
  '/api/image': typeof ApiImageRoute
  '/chapter/$id': typeof ChapterIdRoute
  '/manga/$id': typeof MangaIdRoute
  '/my-chapter/$id': typeof MyChapterIdRoute
  '/my-comic/$id': typeof MyComicIdRoute
  '/api/covers/$': typeof ApiCoversSplatRoute
  '/api/mangadex/$': typeof ApiMangadexSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/adult': typeof AdultRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/upload': typeof UploadRoute
  '/api/image': typeof ApiImageRoute
  '/chapter/$id': typeof ChapterIdRoute
  '/manga/$id': typeof MangaIdRoute
  '/my-chapter/$id': typeof MyChapterIdRoute
  '/my-comic/$id': typeof MyComicIdRoute
  '/api/covers/$': typeof ApiCoversSplatRoute
  '/api/mangadex/$': typeof ApiMangadexSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/adult': typeof AdultRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/upload': typeof UploadRoute
  '/api/image': typeof ApiImageRoute
  '/chapter/$id': typeof ChapterIdRoute
  '/manga/$id': typeof MangaIdRoute
  '/my-chapter/$id': typeof MyChapterIdRoute
  '/my-comic/$id': typeof MyComicIdRoute
  '/api/covers/$': typeof ApiCoversSplatRoute
  '/api/mangadex/$': typeof ApiMangadexSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/adult'
    | '/auth'
    | '/search'
    | '/upload'
    | '/api/image'
    | '/chapter/$id'
    | '/manga/$id'
    | '/my-chapter/$id'
    | '/my-comic/$id'
    | '/api/covers/$'
    | '/api/mangadex/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/adult'
    | '/auth'
    | '/search'
    | '/upload'
    | '/api/image'
    | '/chapter/$id'
    | '/manga/$id'
    | '/my-chapter/$id'
    | '/my-comic/$id'
    | '/api/covers/$'
    | '/api/mangadex/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/adult'
    | '/auth'
    | '/search'
    | '/upload'
    | '/api/image'
    | '/chapter/$id'
    | '/manga/$id'
    | '/my-chapter/$id'
    | '/my-comic/$id'
    | '/api/covers/$'
    | '/api/mangadex/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdultRoute: typeof AdultRoute
  AuthRoute: typeof AuthRoute
  SearchRoute: typeof SearchRoute
  UploadRoute: typeof UploadRoute
  ApiImageRoute: typeof ApiImageRoute
  ChapterIdRoute: typeof ChapterIdRoute
  MangaIdRoute: typeof MangaIdRoute
  MyChapterIdRoute: typeof MyChapterIdRoute
  MyComicIdRoute: typeof MyComicIdRoute
  ApiCoversSplatRoute: typeof ApiCoversSplatRoute
  ApiMangadexSplatRoute: typeof ApiMangadexSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adult': {
      id: '/adult'
      path: '/adult'
      fullPath: '/adult'
      preLoaderRoute: typeof AdultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-comic/$id': {
      id: '/my-comic/$id'
      path: '/my-comic/$id'
      fullPath: '/my-comic/$id'
      preLoaderRoute: typeof MyComicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-chapter/$id': {
      id: '/my-chapter/$id'
      path: '/my-chapter/$id'
      fullPath: '/my-chapter/$id'
      preLoaderRoute: typeof MyChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manga/$id': {
      id: '/manga/$id'
      path: '/manga/$id'
      fullPath: '/manga/$id'
      preLoaderRoute: typeof MangaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapter/$id': {
      id: '/chapter/$id'
      path: '/chapter/$id'
      fullPath: '/chapter/$id'
      preLoaderRoute: typeof ChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image': {
      id: '/api/image'
      path: '/api/image'
      fullPath: '/api/image'
      preLoaderRoute: typeof ApiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mangadex/$': {
      id: '/api/mangadex/$'
      path: '/api/mangadex/$'
      fullPath: '/api/mangadex/$'
      preLoaderRoute: typeof ApiMangadexSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/covers/$': {
      id: '/api/covers/$'
      path: '/api/covers/$'
      fullPath: '/api/covers/$'
      preLoaderRoute: typeof ApiCoversSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdultRoute: AdultRoute,
  AuthRoute: AuthRoute,
  SearchRoute: SearchRoute,
  UploadRoute: UploadRoute,
  ApiImageRoute: ApiImageRoute,
  ChapterIdRoute: ChapterIdRoute,
  MangaIdRoute: MangaIdRoute,
  MyChapterIdRoute: MyChapterIdRoute,
  MyComicIdRoute: MyComicIdRoute,
  ApiCoversSplatRoute: ApiCoversSplatRoute,
  ApiMangadexSplatRoute: ApiMangadexSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
