/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MangaIdRouteImport } from './routes/manga.$id'
import { Route as ChapterIdRouteImport } from './routes/chapter.$id'
import { Route as ApiImageRouteImport } from './routes/api.image'
import { Route as ApiMangadexSplatRouteImport } from './routes/api.mangadex.$'
import { Route as ApiCoversSplatRouteImport } from './routes/api.covers.$'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MangaIdRoute = MangaIdRouteImport.update({
  id: '/manga/$id',
  path: '/manga/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChapterIdRoute = ChapterIdRouteImport.update({
  id: '/chapter/$id',
  path: '/chapter/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageRoute = ApiImageRouteImport.update({
  id: '/api/image',
  path: '/api/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMangadexSplatRoute = ApiMangadexSplatRouteImport.update({
  id: '/api/mangadex/$',
  path: '/api/mangadex/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoversSplatRoute = ApiCoversSplatRouteImport.update({
  id: '/api/covers/$',
  path: '/api/covers/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/api/image': typeof ApiImageRoute
  '/chapter/$id': typeof ChapterIdRoute
  '/manga/$id': typeof MangaIdRoute
  '/api/covers/$': typeof ApiCoversSplatRoute
  '/api/mangadex/$': typeof ApiMangadexSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/api/image': typeof ApiImageRoute
  '/chapter/$id': typeof ChapterIdRoute
  '/manga/$id': typeof MangaIdRoute
  '/api/covers/$': typeof ApiCoversSplatRoute
  '/api/mangadex/$': typeof ApiMangadexSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/search': typeof SearchRoute
  '/api/image': typeof ApiImageRoute
  '/chapter/$id': typeof ChapterIdRoute
  '/manga/$id': typeof MangaIdRoute
  '/api/covers/$': typeof ApiCoversSplatRoute
  '/api/mangadex/$': typeof ApiMangadexSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/search'
    | '/api/image'
    | '/chapter/$id'
    | '/manga/$id'
    | '/api/covers/$'
    | '/api/mangadex/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/search'
    | '/api/image'
    | '/chapter/$id'
    | '/manga/$id'
    | '/api/covers/$'
    | '/api/mangadex/$'
  id:
    | '__root__'
    | '/'
    | '/search'
    | '/api/image'
    | '/chapter/$id'
    | '/manga/$id'
    | '/api/covers/$'
    | '/api/mangadex/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SearchRoute: typeof SearchRoute
  ApiImageRoute: typeof ApiImageRoute
  ChapterIdRoute: typeof ChapterIdRoute
  MangaIdRoute: typeof MangaIdRoute
  ApiCoversSplatRoute: typeof ApiCoversSplatRoute
  ApiMangadexSplatRoute: typeof ApiMangadexSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manga/$id': {
      id: '/manga/$id'
      path: '/manga/$id'
      fullPath: '/manga/$id'
      preLoaderRoute: typeof MangaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapter/$id': {
      id: '/chapter/$id'
      path: '/chapter/$id'
      fullPath: '/chapter/$id'
      preLoaderRoute: typeof ChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image': {
      id: '/api/image'
      path: '/api/image'
      fullPath: '/api/image'
      preLoaderRoute: typeof ApiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mangadex/$': {
      id: '/api/mangadex/$'
      path: '/api/mangadex/$'
      fullPath: '/api/mangadex/$'
      preLoaderRoute: typeof ApiMangadexSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/covers/$': {
      id: '/api/covers/$'
      path: '/api/covers/$'
      fullPath: '/api/covers/$'
      preLoaderRoute: typeof ApiCoversSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SearchRoute: SearchRoute,
  ApiImageRoute: ApiImageRoute,
  ChapterIdRoute: ChapterIdRoute,
  MangaIdRoute: MangaIdRoute,
  ApiCoversSplatRoute: ApiCoversSplatRoute,
  ApiMangadexSplatRoute: ApiMangadexSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
